cart/urls.py
from django.urls import path
from .views import AddToCard, ShopingCartListView, AddCoupon

urlpatterns = [
    path('shopping-cart/', ShopingCartListView.as_view(), name='shoping_cart'),
    path('add-cart/<int:product_id>', AddToCard.as_view(), name='add_to_cart'),
    path('add-coupon', AddCoupon.as_view(), name='add_coupon'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from custom_auth.views import (SignUpCreateView, UserLoginView, UserLogoutView, UserPasswordChangeView, HomeView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    # Authentication urls.
    path('signup/', SignUpCreateView.as_view(), name='user_signup'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='user_password_change'),
    # User Profile usls.
    path('user-profile/', include('user_profile.urls')),
    # Products Urls
    path('products/', include('product.urls')),
    # cart urls
    path('cart/', include('cart.urls')),
    # order urls
    path('orders/', include('order.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# ADMIN PANEL HEADER AND TITLE TEXT CHANGE.
admin.site.site_header = "E-Commerce Admin"
admin.site.site_title = "E-Commerce Admin Portal"
admin.site.index_title = "Welcome to E-Commerce Portal"


# Custom erorrs Page
handler404 = 'custom_auth.views.custom_page_not_found'
handler500 = 'custom_auth.views.custom_server_error'
handler403 = 'custom_auth.views.custom_permission_denied_view'
handler400 = 'custom_auth.views.custom_bad_request_view'

cart/models.py
from django.db import models

# Create your models here.
class Coupon(models.Model):
    code = models.CharField(max_length=25)
    discount = models.PositiveIntegerField(help_text='Discount in percentage')
    active = models.BooleanField(default=True)
    active_date = models.DateField()
    expiry_date = models.DateField()
    required_amount_use_coupon = models.PositiveBigIntegerField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.code

order/models.py
from django.db import models 
from product.models import Product
from cart.models import Coupon
from django.contrib.auth import get_user_model
User = get_user_model()


class StatusOptions(models.TextChoices):
    """ CONSTANT = DB_VALUE, USER_DISPLAY_VALUE  """
    RECEIVED = 'received', 'Received'
    ON_WAY = 'on the way', 'On The Way'
    DELIVERED = 'delivered', 'Delivered'


# Create your models here.
class OrderItem(models.Model):
    product = models.ForeignKey(Product, related_name='ordered', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.title} x {self.quantity}"


class Order(models.Model):
    user = models.ForeignKey(User, related_name='orders', on_delete = models.CASCADE)
    order_items = models.ManyToManyField(OrderItem)
    coupon = models.ForeignKey(Coupon, null=True, blank=True, on_delete=models.SET_NULL)
    discount_amount = models.DecimalField(max_digits=8, decimal_places=2)
    shipping_charge = models.DecimalField(max_digits=8, decimal_places=2)
    total_amount = models.DecimalField(max_digits=8, decimal_places=2)
    paid = models.BooleanField(default=True)
    transaction_id = models.UUIDField()
    paypal_transaction_id = models.CharField(max_length=30)
    paid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    status = models.CharField(max_length=15, choices=StatusOptions.choices)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.PROTECT,  related_name='updated_%(class)ss', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

product/models.py
from django.db import models
from django.contrib.auth import get_user_model
from custom_auth.validator import image_validator
from django.utils.html import format_html
User = get_user_model()

# Create your models here.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='created_%(class)ss')
    updated_by = models.ForeignKey(User, on_delete=models.PROTECT,  related_name='updated_%(class)ss', null=True, blank=True)

    class Meta:
        abstract = True

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in self.__class__.__name__._meta.fields]


class Product(BaseModel):
    title = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True)
    stock = models.DecimalField(max_digits=8, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    thumbnail = models.ImageField(upload_to='product_images/', validators=[image_validator], blank=True, null=True, help_text='Must be .jpeg .jpg .png Format and Size should not exceed 2 MiB.')

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.title
    
    def product_image(self):
        return format_html('<img src="/media/{}" width = "50" height = "50"/>', self.thumbnail)

cart/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect,redirect
from django.db.models import Q, Prefetch, Sum, Value
from django.views import generic
from datetime import datetime
from django.utils import timezone
from django.contrib import messages
from product.models import Product
from .carts import Cart
from .models import Coupon


def format_search_string(fields, keyword):
    Qr = None
    for field in fields:        
        q = Q(**{"%s__icontains" % field: keyword })
        if Qr:
            Qr = Qr | q
        else:
            Qr = q    
    return Qr

# Create your views here.
class AddToCard(generic.View):
    def get(self, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs.get('product_id'))
        cart = Cart(self.request)
        cart.update(product.id, 1)
        return redirect('shoping_cart')


class ShopingCartListView(generic.ListView):
    permission_required = 'eshop.view_product'
    model = Product
    context_object_name = 'items'
    paginate_by = 9
    template_name = 'eshop/cart.html'
    queryset = Product.objects.all()
    search_fields = ['title', 'category__title']
    
    def get(self, request, *args, **kwargs):
        product_id = request.GET.get('product_id')
        quantity = request.GET.get('quantity')
        cart = Cart(self.request)
        print(cart.coupon, "Coupon")
        if product_id and quantity:
            # product = get_object_or_404(Product, pk=kwargs.get('product_id'))
            cart.update(int(product_id), int(quantity))
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
        else:
            return super().get(request, *args, **kwargs)
    
    
    def get_queryset(self):
        queryset = super().get_queryset()
        
        query_param = self.request.GET.copy()
        search_param = query_param.get('query', None)
        if search_param:
            Qr = format_search_string(self.search_fields, search_param)
            queryset = queryset.filter(Qr)

        return queryset
    

class AddCoupon(generic.View):
    def post(self, *args, **kwargs):
        code = self.request.POST.get('coupon_code')
        coupon = Coupon.objects.filter(code__iexact=code, active=True)
        cart = Cart(self.request)

        if coupon.exists():
            coupon = coupon.first()
            current_date = datetime.date(timezone.now())
            active_date = coupon.active_date
            expiry_date = coupon.expiry_date

            if current_date > expiry_date:
                messages.warning(self.request, "Coupon Expired!")
                return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
            
            if current_date < active_date:
                messages.warning(self.request, "Coupon is yet to be available")
                return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
            
            if cart.actual_total() < coupon.required_amount_use_coupon:
                messages.warning(self.request, f"Your have to shop at least ${coupon.required_amount_use_coupon} to use this coupon code!")
                return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

            cart.add_coupon(coupon.id)
            messages.success(self.request, "Your Coupon has been included Successfully.")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))
        else:
            messages.warning(self.request, "Invalid Coupon Code!")
            return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

templates/eshop/careousel.html
{% load static %}

<div id="header-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" style="height: 410px;">
            <img class="img-fluid" src="img/carousel-1.jpg" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="p-3" style="max-width: 700px;">
                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashionable Dress</h3>
                    <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                </div>
            </div>
        </div>
        <div class="carousel-item" style="height: 410px;">
            <img class="img-fluid" src="img/carousel-2.jpg" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="p-3" style="max-width: 700px;">
                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                    <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
        <div class="btn btn-dark" style="width: 45px; height: 45px;">
            <span class="carousel-control-prev-icon mb-n2"></span>
        </div>
    </a>
    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
        <div class="btn btn-dark" style="width: 45px; height: 45px;">
            <span class="carousel-control-next-icon mb-n2"></span>
        </div>
    </a>
</div>

templates/eshop/cart.html
{% extends 'eshop/index.html' %}
{% load static %}

{% block navbar %}
    <!-- Navbar Start -->
    {% include 'eshop/navbar_fixed.html' %}
    <!-- Navbar End -->
{% endblock navbar %}

{% block content %}
    {% if cart %}
    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Image</th>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in cart %}
                        {% with product=item.product %}
                        <tr>
                            <td class="align-middle"><img src="{{ product.thumbnail }}" alt="thumbnail" style="width: 50px;"></td>
                            <td class="text-left">
                                <a href="{% url 'product_details' product.id %}" class="text-left btn btn-sm text-dark p-0">
                                {{ product.title }}
                                </a>
                            </td>
                            <td class="align-middle">${{ product.price|floatformat:"2" }}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <a href="?product_id={{ product.id }}&&quantity=-1" class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </a>
                                    </div>
                                    <input type="text" disabled class="form-control form-control-sm bg-secondary text-center" value="{{ item.quantity }}">
                                    <div class="input-group-btn">
                                        <a href="?product_id={{ product.id }}&&quantity=1" class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">${{ item.sub_total|floatformat:"2" }}</td>
                            <td class="align-middle">
                                <a href="?product_id={{ product.id }}&&quantity=-{{ item.quantity }}" class="btn btn-sm btn-primary btn-plus">
                                    <i class="fa fa-times"></i>
                                </a>
                            </td>
                        </tr>
                        {% endwith %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-5" action="{% url 'add_coupon' %}" method="POST">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="coupon_code" class="form-control p-4" placeholder="Coupon Code" Required>
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            <h6 class="font-weight-medium">${{ cart.actual_total|floatformat:"2" }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">${{ shipping|floatformat:"2" }}</h6>
                        </div>
                        {% if cart.total_discount %}
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Discount</h6>
                            <h6 class="font-weight-medium">${{ cart.total_discount|floatformat:"2" }}</h6>
                        </div>
                        {% endif %}
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">${{ cart.grand_total|floatformat:"2" }}</h5>
                        </div>
                        <a href="{% url 'checkout' %}" class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
    {% else %}
    {% include 'eshop/empty_cart.html' %}
    {% endif %}
{% endblock content %}    

templates/eshop/empty_cart.html
{% load static %}

<!-- Contact Start -->
<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <i class="fa fa-exclamation-triangle fa-3x text-primary d-block mb-3"></i>
        <h2 class="section-title px-5"><span class="px-2">Your Cart is Empty</span></h2>
        <h6 class="font-weight-semi-bold mb-3">Add something to make me happy :)</h6>
        <a href="{% url 'product_list' %}" class="btn btn-primary my-3 py-3">Continue Shopping</a>
    </div>
</div>
<!-- Contact End --> 

templates/eshop/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
            </a>
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                by
                <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'eshop/img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

templates/eshop/js.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'eshop/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'eshop/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'eshop/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'eshop/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'eshop/js/main.js' %}"></script>

templates/eshop/navbar.html
{% load static %}
<!-- Navbar Start -->
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown">Dresses <i class="fa fa-angle-down float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                            <a href="" class="dropdown-item">Men's Dresses</a>
                            <a href="" class="dropdown-item">Women's Dresses</a>
                            <a href="" class="dropdown-item">Baby's Dresses</a>
                        </div>
                    </div>
                    <a href="" class="nav-item nav-link">Shirts</a>
                    <a href="" class="nav-item nav-link">Jeans</a>
                    <a href="" class="nav-item nav-link">Swimwear</a>
                    <a href="" class="nav-item nav-link">Sleepwear</a>
                    <a href="" class="nav-item nav-link">Sportswear</a>
                    <a href="" class="nav-item nav-link">Jumpsuits</a>
                    <a href="" class="nav-item nav-link">Blazers</a>
                    <a href="" class="nav-item nav-link">Jackets</a>
                    <a href="" class="nav-item nav-link">Shoes</a>
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'product_list' %}" class="nav-item nav-link">Shop</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0">
                        {% if request.user.is_authenticated %}
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ request.user.get_short_name }}</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'order_list' %}" class="nav-item nav-link">Orders</a>
                                {% if request.user.userprofile %}
                                <a href="{% url 'user_profile_update' request.user.userprofile.pk %}" class="nav-item nav-link">Update Profile</a>
                                {%endif%}
                                <a href="{% url 'user_password_change' %}" class="nav-item nav-link">Change Password</a>
                                <a href="{% url 'user_logout' %}" class="nav-item nav-link">Logout</a>
                            </div>
                        </div>
                        {% else %}
                        <a href="{% url 'user_login' %}" class="nav-item nav-link">Login</a>
                        <a href="{% url 'user_signup' %}" class="nav-item nav-link">Register</a>
                        {% endif %}
                        
                    </div>
                </div>
            </nav>

            <!-- careousel Start -->
            <!-- careousel End -->
        </div>
    </div>
</div>
<!-- Navbar End -->

templates/eshop/order_detail.html
{% extends 'eshop/index.html' %}
{% load static %}

{% block navbar %}
    <!-- Navbar Start -->
    {% include 'eshop/navbar_fixed.html' %}
    <!-- Navbar End -->
{% endblock navbar %}

{% block content %}
    <!-- Shop Detail Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col-lg-12 pb-5">
                <div class="text-center mb-4">
                    <h2 class="section-title px-5"><span class="px-2">{{ title }}</span></h2>
                    <div class="row">
                        <div class="col-md-12 text-left">
                            <h4><span class="px-2">Customer Information</span></h4>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item px-0">
                                    Name: {{ instance.user.get_full_name }}
                                </li>
                                <li class="list-group-item px-0">
                                    Address: {{ instance.user.userprofile.billing_address }}
                                </li>
                                <li class="list-group-item px-0">
                                    Phone: {{ instance.user.userprofile.phone_number }}
                                </li>
                                <li class="list-group-item px-0">
                                    Email: {{ instance.user.email }}
                                </li>
                                <li class="list-group-item px-0">
                                    Transaction Id: {{ instance.transaction_id }}
                                </li>
                            </ul> 
                        </div>
                    </div>
                </div>
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Image</th>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in instance.order_items.all %}
                        <tr>
                            <td class="align-middle"><img src="/media/{{ item.product.thumbnail }}" alt="thumbnail" style="width: 50px;"></td>
                            <td class="text-left text-wrap">
                                <a href="{% url 'product_details' item.product.id %}" class="text-left btn btn-sm text-dark p-0">
                                {{ item.product.title }}
                                </a>
                            </td>
                            <td class="align-middle">${{ item.product.price|floatformat:"2" }}</td>
                            <td class="align-middle">
                                {{ item.quantity }}
                            </td>
                            <td class="align-middle">${{ item.price|floatformat:"2" }}</td>
                        </tr>
                        {% endfor %}
                        {% if instance.coupon %}
                        <tr>
                            <td class="text-right" colspan="4"> Discount {{ instance.coupon.discount }} % </td>
                            <td>${{ instance.discount_amount }}</td>
                        </tr>
                        {% endif %}
                        <tr>
                            <td class="text-right" colspan="4"> Shipping </td>
                            <td>${{ instance.shipping_charge }}</td>
                        </tr>
                        <tr>
                            <td class="text-right" colspan="4"> Grand Total </td>
                            <td>${{ instance.total_amount }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->
{% endblock content %}